lib/oelite/baker.py
lib/oelite/cmd/bake.py

Allow specifying number of lines to show (at the end of the build) from
each logfile of failed tasks.  Default is set to 42 lines.
This supersedes PR #5.

lib/oelite: Add --debug-loglines argument to bake command

---

classes/sdk-image.oeclass

sdk-image: Fix wrapping of gcc binaries in libexec/

---

classes/kernel.oeclass

This fixes the kernel recipe when USE_kernel_uimage_loadaddr is not set and USE_kernel_uimage_entrypoint is set.

Fix LOADADDR for USE_kernel_uimage_entrypoint

---

classes/kbuild.oeclass
classes/kernel-common.oeclass
classes/kernel-modules.oeclass
lib/oelite/parse/oeparse.py

PLY >= 3.6 uses a set instead of a dict for the lextokens. It's just used as a list in the end, so check the type of the return value to determine how to convert the data.

Issue #27: ply compatibility

---

classes/dupdate-image.oeclass

Set default value to "0", and allow override in recipe.

class/dupdate-image: Allow override of dupdate_version default USE value

---

recipes/eglibc/eglibc-2.18/circular_dependency.patch
recipes/eglibc/eglibc_2.18-r24943.oe

A circular dependency in Makefile/Makerules can cause the
build to fail.
The patch is based on 5f855e3598a576c35e54623a13b256f3e87fcd4d from
glibc repository.
The change is included in glibc-2.19 and onwards.
Signed-off-by: Klaus Henning Sorensen <klaus.sorensen@prevas.dk>

Add patch to resolve circular dependency in Makefile

---

recipes/eglibc/eglibc-2.18/gettimeofday_time.patch
recipes/eglibc/eglibc_2.18-r24943.oe

On powerpc32, internal calls to gettimeofday and time got
resolved to placeholder versions of these library calls
which return bogus data.
Based on 736c304a1ab4cee36a2f3343f1698bc0abae4608 in glibc.
Fixed in glibc 2.19.
Signed-off-by: Klaus Henning Sorensen <klaus.sorensen@prevas.dk>

Fix for gettimeofday and time for powerpc32

---

classes/image_depmod.oeclass

When collecting modules from out-of-tree builds, one must run depmod at
image creation time to resolve module dependencies. E.g. with wifi
drivers from linux-backports fails to load at first boot if dependencies
are missing.

image_depmod: add class to run depmod on image modules

---

lib/oelite/function.py
lib/oelite/task.py

lib/oelite: Use date-time stamp for .log and .run files
Example:
new: do_configure.20151213141516.run   (2015/12/13 14:15:16)
old: do_configure.32768.run
This replaces the PID based filename which was not uniqe and
resulted in .log and .run files being overwritten (especially if running
oe bake in docker). The UTC timestamp is more likely to generate a uniqe
file. (except on build hosts with broken/no RTC, during local hard time
adjustments, leap second, ...)

Log and tmp file handling

---

recipes/glibc/glibc-2.21/avoid_assert_on_incompatible_locale_settings.patch
recipes/glibc/glibc_2.21.oe

Without this patch, binaries in the SDK will fail like:
".arm-cortexa9neon-linux-gnueabi-as: loadlocale.c:130:
_nl_intern_locale_data: Assertion `cnt < (sizeof
(_nl_value_type_LC_COLLATE) / sizeof
(_nl_value_type_LC_COLLATE[0]))' failed."
on modern Linux hosts. patch taken from upstream.

glibc: add patch to avoid asserting in SDK binaries

---

classes/image_mdev.oeclass

Add post rstage function to add entries from USE_image_mdev_nodes
in etc/mdev.conf.
To make sure the entries are added after any recipe defined sections,
the existing image_preprocess_mdev() function in IMAGE_PREPROCESS_FUNCS
is changed to run as post rstage, as the newly created do_rstage_mdev()
function is written in python.
The function reads entries in USE_image_mdev_nodes and creates appends
lines to etc/mdev.conf with the configured match-strings and group-spec,
bases on the following syntax:
<match>:<group>
Example setting in e.g. distro configuration:
DISTRO_USE_image_mdev_nodes = "spidev.*:spi"

image_mdev.oeclass: support use flag entries in mdev.conf

---

classes/image_passwd.oeclass

Add post rstage functions to create users and groups listed in
USE_image_passwd_users and USE_image_passwd_groups, respectively.
In order to actually include the created users/groups in the final
image, the functions are run as postfuncs in the rstage step, and they
work on etc/passwd and etc/group in the rstage dir. This is needed
because the do_compile step moves the contents from ./rstage to ./image
and creates the image without possibility to inject python functions in
between. This also requires changing the existing
image_preprocess_passwd() function to run as rstage postfunc instead of
"IMAGE_PREPROCESS_FUNCS", in order to have its created users/groups
available when parsing the mentioned use flags.
Example user configartion in e.g. a distro configuration: …

image_passwd.oeclass: support use flag creation of users/groups

---

classes/largefile.oeclass

Make sure we enable largefile support when the useflag is enabled
by forcing largefile specific autotools flags to the correct settings.
without this e.g. libsndfile would not be built with largefile
support even though the configure switch was on.

largefile: enforce largefile autotools flags

---

conf/provided/all.conf
conf/provided/osx.conf

Remove from provide.conf and therby use the oe-lite build zip and libz versions.
zip and libz is not directly mentioned in the setup/* files so no cleanup needed there.

Remove zip and libz from provides.conf

---

classes/runit.oeclass

In a recipe with a 'foobar' service, controlled by the USE_foobar_runit
flag, adding a USE_foobar_runit_down flag, and enabling it will cause a
down file to be created in the service dir, and thus prevent the service
from being started automatically.

class/runit: Add support for creating service down file with USE flag

---

recipes/gcc/gcc.inc

gcc: Fix MinGW gcc builds (needs libwinpthread-1.dll to run)

---

classes/autotools-autoreconf.oeclass
classes/gettext.oeclass
conf/provided/all.conf
conf/provided/default.conf
conf/provided/minimal.conf
conf/provided/osx.conf
recipes/bc/bc.inc
recipes/binutils/binutils.inc
recipes/gmp/gmp.inc

This is a cherry pick of most of the commits in the old PR #13 from @diorcety.

Cherry-pick of commits from old PR #13

---

recipes/mingw-w64/mingw-w64-crt.inc

When building with parallel make, mingw sometimes fails with the error
below. Same issue has been reported in crosstool-ng:
https://github.com/crosstool-ng/crosstool-ng/issues/246
Stabilize building of mingw-w64-crt by disabling parallel builds.
make[3]: Entering directory `/oe-lite/tmp/work/sdk/i686-sdk_mmx-mingw32/mingw-w64-crt-3.1.0/build/mingw-w64-crt'
i686-sdk_mmx-mingw32-gcc -E -x c /oe-lite/tmp/work/sdk/i686-sdk_mmx-mingw32/mingw-w64-crt-3.1.0/src/mingw-w64-v3.1.0/mingw-w64-crt/lib32/msvcrt.def.in -Wp,-w -I/oe-lite/tmp/work/sdk/i686-sdk_mmx-mingw32/mingw-w64-crt-3.1.0/src/mingw-w64-v3.1.0/mingw-w64-crt/def-include | /bin/sed 's/^#/;/' >lib32/msvcrt.def
/bin/sh: lib32/msvcrt.def: No such file or directory
/oe-lite/tmp/work/sdk/i686-sdk_mmx-mingw32/mingw-w64-crt-3.1.0/src/mingw-w64-v3 …

mingw-w64-crt: disable parallel make

---

conf/provided/all.conf
conf/provided/default.conf
conf/provided/minimal.conf

By rewriting all.conf to amend default.conf, and default.conf to amend
minimal.conf, it should be easier to make consistent changes to these
in the future.
As a consequence of this change, native:zip is dropped from minimal.conf
and default.conf, as it was already removed from all.conf
(see 367b92d25983bf48647e4528897aa2d3ddde9425).

conf/provided: Align minimal.conf, default.conf and all.conf

---

classes/application-pkg.oeclass

- Use the new default file extension for images
- Remove crosstool-NG leftovers

application-pkg.oeclass: bugfixes

---

classes/cpio-image.oeclass
classes/kernel.oeclass
classes/sdk-image.oeclass
classes/u-boot.oeclass
classes/uimage-fit.oeclass

Allows different naming of u-boot-tools recipe and other provides of the
util. This patch removes all hardcoded u-boot-tools-* .

classes: Use util/mkimage in dependencies

---

classes/s6rc.oeclass

This class allows management of s6-rc services, which are in the
daemontools family (ie. similar to runit), but with additional features
such as dependencies, one-time initialization scripts.
See http://skarnet.org/software/s6-rc/ for more details.

class/s6rc: Management of s6-rc services

---

recipes/gcc/gcc-bootstrap.inc
recipes/gcc/gcc-common.inc
recipes/gcc/gcc.inc
recipes/glibc/glibc.inc

The glibc recipe unconditionally disables use of
-fstack-protector. That's a bit unfortunate, because upstream glibc
tries to use that for some security-critical components
(e.g. resolv). It does not enable it for all of glibc, as that would
imply a significant performance loss.
The reason for this disabling is not obvious from the git history, but
it was presumably done as a hack to simply make glibc build (or
rather: link). However, the problem is really in gcc: gcc, at the
linking stage, needs to know whether the target libc has the
infrastructure to support the -fstack-protector instrumentation. But
the autodetect in the configure stage of gcc cannot possibly work when
the target glibc doesn't even exist yet. So we need to make sure that
the configure variable gcc_cv_libc_provides_ssp …

gcc, glibc: fix bootstrapping -fstack-protector detection and use

---

classes/kernel.oeclass

The do_install_kernel rule apparently tries to copy a minimal set of
files allowing building out-of-tree modules. However, when trying to
compile a module against kernel 4.1.15, I hit:
arch/x86/Makefile:66: arch/x86/Makefile_32.cpu: No such file or directory
I think this is related to kernel commit
a436bb7b806383ae0593cab53d17fc9676270cd3 (kbuild: use relative path
more to include Makefile), which changed the line including
Makefile_32.cpu like this:
-        include $(srctree)/arch/x86/Makefile_32.cpu
+        include arch/x86/Makefile_32.cpu
This is a band aid-and-chewing gum patch which fixes the problem for
me, but I'm sure there is a better and less fragile solution.

kernel.oeclass: fix for building out-of-tree module on x86_32

---

conf/oelayout.conf

Change to weak assignment, allowing override of a number of basic dir
variables using ENV variables.

Allow override of TMPDIR, IMAGE_DEPLOY_DIR and more

---

lib/oelite/baker.py

This fixes some cases where recipes marked with REBUILD="1" (fx. anything
inheriting image.oeclass) were not rebuild.

lib/oelite: Fix false skipping of REBUILD marked recipes

---

classes/image.oeclass
classes/stage.oeclass

This add support for blacklisting of packages for rstage, which has been
used since at least 2011 to handle differences between differences in
dependencies in rootfs and initramfs.
Ideally, we should have support for using multiple distros (or something
like that), so that initramfs and rootfs could use different distro
configuration, while still being build as a single image.
But until then, this seems like the best solution we have been able to
come up with, so let's get it merged.

image: Package blacklist for rstage

---

recipes/base-version/base-version.oe

Contained the ctng configuration before. Since we no longer use ctng,
remove it
Signed-off-by: Christian Sørensen <christian.braunersorensen@prevas.dk>

base-version: Removed gcc-cross-config. It not present with never toolchain

---

classes/binconfig.oeclass

When running glob.glob() in python, the call does a search on the file
system to expand wildcards to matching files. This failed in binconfig
due to globing relative to the source directory and the removal of
heading slashes (i.e. '/usr/bin/*-config' -> 'usr/bin/*-config'.
Fix this by changing working directory prior to the globing, so that the
search is done relative to the install directory.

binconfig.oeclass: fix file globbing in do_install_binconfig_fixup

---

lib/oelite/baker.py
lib/oelite/meta/dict.py
lib/oelite/meta/meta.py
lib/oelite/task.py

We spend longer on the initial part of 'oe bake' than we should; that's particularly annoying when there's actually nothing to do. These are just a few low-hanging fruits, and I freely admit that the last patch is really ugly, but OTOH that's what gives the largest improvement.
Master + the just the first patch:
$ time oe bake gnutls
Adding recipes to cookbook: 233 / 233 [100 %]
Building dependency tree time 1.114 seconds
Calculating task metadata hashes: 405 / 405 [100 %]
Calculation task metadata hashes time 6.266 seconds
Nothing to do
real    0m9.760s
user    0m9.500s
sys     0m0.244s
With all these:
$ time oe bake gnutls
Adding recipes to cookbook: 233 / 233 [100 %]
Building dependency tree time 1.117 seconds
Calculating task metadata hashes: 405 / 405 [100 %]
Calculation task …

Faster metadata hashing

---

lib/oelite/cookbook.py

None complete cache files were made in case a recipe wasn't compatible
with our setup. I.e. if a COMPATIBLE_IF_FLAG was set but the corresponding
'compatible' USE-flag wasn't defined.
Reading incomplete cache files resulted in not relevant warning-noice

cookbook: Avoid writing none complete cache file by not writing any thing at all

---

recipes/fakeroot/fakeroot.inc

fakeroot depends on host libacl1-dev to set correct permissions on
files/folders.
If libacl1-dev is not available, all folders/files are root-only
writable.

fakeroot: add correct dependencies.

---

lib/oelite/runq.py

During my "make it faster" efforts, I stumbled on this, which I'm sending by itself since I believe it is highly unlikely to break anything and obviously a huge win.
Creating an index cuts over 75% of the "Building dependency tree
time", from ~6m04s to ~1m29s.

oelite: runq.py: add an index to the recdepend table

---

lib/oelite/cookbook.py
lib/oelite/meta/dict.py
lib/oelite/meta/meta.py
lib/oelite/parse/oelex.py
lib/oelite/parse/oeparse.py

This is morally identical to the patches in PR #131, but rebased on top of current master (to fix up some conflicts with PR #132 which was merged in the meantime). Submitting again hoping that the openssl issue is now gone. Original pull request text:
These patches reduce the memory footprint of oelite by about 35%, measured immediately after the task metadata hash computation is done. They do not have any measurable effect on the run time of a "oe bake machine" when machine is already fully built (see below for details). I do believe that the runtime of an actual build will decrease when the kernel has more RAM (on my machine, on the order of an extra 1.5% of total memory, or about 240MiB) to play with for page cache etc. instead of having it tied up in a process which will mostly never …

Memory use reduction, v4

---

classes/kernel.oeclass

To enable set use flag kernel_trace

kernel.oeclass: Added package 'trace' for keeping traceevent libraries.

---

classes/binconfig-stage.oeclass

When staging packages that inherit binconfig, binconfig_stage_fixup() is
called to create a symlink:
./stage/cross/${bindir}/${PN}-config -> ./stage/machine/${bindir}/${PN}-config
When binconfig_stage_fixup() is called the destination directory for the
symlink (./stage/cross/${bindir}) might not exist, in which case the
symlink creating fails. This is the case when the first dependency being
stages uses binconfig-fixup.
Simply fix this by always creating the destination directory before
symlinking.

classes/binconfig-stage: create destination dirs before symlinking

---

conf/provided/all.conf
conf/provided/default.conf

As fakeroot as of 53e6e982456e depends on libacl1-dev, and we do not
have a recipe for this, default is not usable at all without it.
For conf/provided/all.conf, libacl1-dev was added in 367b92d25983b
(although the PR comments suggested that it was moved to another commit).

conf/provided: Make default usable again

---

lib/oelite/fetch/git.py

This was done to avoid the following error:
/build/ingredients/glibc/git/git_sourceware.org_git_glibc.git> git remote update
Fetching origin
From git://sourceware.org/git/glibc
...
error: 'refs/heads/hjl/memcpy' exists; cannot create 'refs/heads/hjl/memcpy/dpdk/master'
! [new branch]      hjl/memcpy/dpdk/master -> hjl/memcpy/dpdk/master  (unable to update local ref)
...
error: some local refs could not be updated; try running
'git remote prune origin' to remove any old, conflicting branches
error: Could not fetch origin
Error: git update failed (required rev could not be fetched)
Signed-off-by: Sean Nyekjaer <sean.nyekjaer@prevas.dk>

gitfetcher: Added git prune origin call before git remote update

---

classes/auto-package-libs.oeclass

Currently, one could achieve rougly the same thing by overriding
AUTO_PACKAGE_LIBS_LIBDIR, setting it to e.g. "${libdir}:myprefix
${sharedlibdir}:myprefix", but it's a lot more convenient to be able
to set the default prefix independently from the libdirs.
The use case is e.g. libunwind, which generates libraries
libunwind.so, libunwind-setjmp.so, libunwind-ptrace.so,
libunwind-coredump.so etc. Rather than making AUTO_PACKAGE_LIBS
contain "unwind-setjmp unwind-ptrace" with corresponding packages
"libunwind-libunwind-setjmp" etc, it's more convenient to set both
PROVIDEPREFIX and LIBPREFIX to "${PN}-" and PKG_PREFIX to "", and then
just list the shorter names "setjmp ptrace" etc. in
AUTO_PACKAGE_LIBS. That way, we get a package "libunwind-ptrace" which
provides "libunwind-ptrace.so". …

auto-package-libs.oeclass: allow configuring libprefix

---

lib/oelite/parse/oeparse.py

Looking through a 38.5M line strace dump, I stumbled on a curious lstat call:
15902 lstat("f", 0x7ffda7538660)        = -1 ENOENT (No such file or directory) <0.000005>
A few syscalls above we've done a getcwd revealing that we're in the
manifest dir. So why on earth do we do this?
The clue came when further down I found an lstat of "s": In the first
case above, we were doing core/conf/fetch/sourceforge.conf, while in
the "s" case we were processing core/classes/c++.oeclass. This
suggests doing
git grep -E '\[-1'
which quickly points to this chunk of code.
It's a bit sad losing the prank of doing
ln -s meta/core/conf/fetch/sourceforge.conf f
on a coworker's computer while he's grabbing coffee and see how long
it takes him to figure out what went wrong...
Anyway, if someone feels a check …

oeparse.py: remove useless semi-dead code

---

recipes/gcc/gcc-common.inc
recipes/gcc/gcc.inc

Move .dll files to sharedlibdir (bin), as they need to be in %PATH%.
Sorry for moving the files around manually, but I did not manage to find
a proper way to convince gcc build system to place them correctly :(

gcc: Fix mingw DLL packaging

---

lib/oelite/git.py

This is similar to PR #143, but where #143 fixed it for mirror task,
this does the same for fetch task.

lib/oelite: Also prune git remotes on fetch

---

classes/image_passwd.oeclass
classes/passwd.oeclass

There's a bug in the current avahi recipe: The autoipd-passwd and
daemon-passwd files end up being packaged under the names avahi.1 and
avahi.2, but in the packages' respective FILES_* list they list each
others' files. This means that when one includes one but not the other
package, the expected user account is missing from the system.
Having to manually enumerate the PASSWD_FILES the same way the passwd
class does it is rather fragile. So instead of renaming the files to
${PN}.${i}, put each recipe's passwd files in the subdirectory ${PN} and
keep the file's basename. That makes the relevant FILES entries much
more predictable.
While at it, replace $cwd with . in image_passed.oeclass - avoiding
long absolute paths makes it easier to read the log output.

passwd classes: make them more robust

---

classes/kernel-common.oeclass

It does not make sense that EXTRA_OEMAKE is overwritten if recipe sets
EXTRA_OEMAKE prior to inheriting kernel class.
This change is technically not backwards compatible though!

class/kernel: Don't overwrite EXTRA_OEMAKE

---

lib/oelite/fetch/git.py

When a recipe try to use git fetch, with a revision or tag that does not exist in that checkout, the fetch will fail without any information about why it failed.

fetch/git.py: write to log when branch, rev or tag not found

---

lib/oelite/fetch/url.py

It turns out that the urlgrabber module is responsible for pulling in
about half the shared objects we use. If we have all ingredients
downloaded already, there's no reason for polluting our VM with all
that.
Fortunately, we only use urlgrabber in a single function, so this is a
rather small patch.
We end up having 149 fewer entries in /proc/self/maps (178 vs 327),
accounting for 147 MiB of address space.
To see how much a large VM affects fork() cost one can play with this
little script:
#!/usr/bin/python
import os
import sys
#import pysvn
count = 0
size = 0
with open("/proc/self/maps") as f:
for l in f:
print l,
r, rest = l.strip().split(" ", 1)
begin,end = r.split("-")
count += 1
size += int(end, 16) - int(begin, 16)
print "%d VMAs, total size %d KiB" % (count, size/1024) …

oelite/fetch/url.py: lazily import urlgrabber

---

lib/oelite/fetch/svn.py

Our memory footprint is still humongous, but for now I'm out of ideas
for reducing the size of python objects. Looking at /proc/self/maps,
however, reveals that pysvn is responsible for pulling in lots of
shared libraries. Since there isn't a single recipe currently relying
on the svn fetcher, I think this little piece of complexity is worth
it.
Comparing the maps file before and after shows that we save around 93
VMAs covering 74 MiB of address space. That's a lot of pages to avoid
COW'ing for every fork() we do.
I originally did the lazy import in the __init__ method, but then we
don't save anything if there is a recipe with an svn url, even if
we're not actually building that recipe (the import would happen
during recipe parsing).
I've tested this by reinstating the eglibc recipe as it …

oelite/fetch/svn.py: import pysvn lazily

---

classes/auto-package-utils.oeclass

Some binaries change behaviour based on argv[0], and those utilities
often come with a bunch of symlinks pointing to the same binary. With
the current auto_package_utils, these symlinks usually end up as
dangling links in the main package with no tie to the actual package
providing the binary.
Adding the symlink names to the AUTO_PACKAGE_UTILS var is not really a
solution, as that would just create new packages containing dangling
links.
One could do something like
FILES_xz-xz += "/usr/bin/lzcat"
FILES_xz-xz += "/usr/bin/lzma"
FILES_xz-xz += "/usr/bin/unlzma"
FILES_xz-xz += "/usr/bin/unxz"
FILES_xz-xz += "/usr/bin/xzcat"
but that doesn't tell the world that the xz-xz package actually
provides util/lzma.
So this implements support for spelling the above
AUTO_PACKAGE_UTILS_SYMLINKS_xz = …

auto_package_utils.oeclass: add AUTO_PACKAGE_UTILS_SYMLINKS_* feature

---

recipes/readline/readline-6.2/0000-curses-link.patch
recipes/readline/readline.inc

readline needs ncurses for termcap, so we actually needs to link
with it and add it to RDEPENDS.
configure for readline is broken so we have to hard add linking with
ncurses.
Signed-off-by: Sean Nyekjaer sean@nyekjaer.dk

readline: link with ncurses

---

lib/oelite/baker.py
lib/oelite/compat.py
lib/oelite/cookbook.py
lib/oelite/function.py
lib/oelite/oven.py
lib/oelite/priq.py
lib/oelite/profiling.py
lib/oelite/runq.py
lib/oelite/task.py
lib/oelite/util.py

This is a complete branch getting to parallel task execution. The first 13 commits are identical to PR#168 (except for a rebase to current master).
The diffstat shows that we exclusively touch files under lib/oelite, and I've doublechecked that this doesn't change meta-data hashes (by doing oe bake world on master, checking out this branch, and seeing that oe bake world says "nothing to do").
There are admittedly some leftovers from the development (such as initially setting the oven capacity to a hardcoded 8, later changing that to something based on $PARALLEL_MAKE), and I'm open to reordering/squashing/etc. But I'm not doing that unless some reviewer finds it important and points out specific problems. AFAICT, the worst issue is the "temporary" disabling of --fake-build, which doesn't …

All the way to parallel tasks, and a little beyond

---

classes/core.oeclass
lib/oelite/meta/dict.py

These patches reduce the (anonymous) memory footprint of the oe-lite process by about 100MiB (~14%) for an oe bake world. They do not change metadata hashes.

Some memory use reduction

---

lib/oelite/meta/dict.py

This saves another 5+ MiB of memory.

oelite/meta/dict.py: don't expand python code in _fill_expand_cache

---

lib/oelite/meta/meta.py
lib/oelite/task.py

This seems to cut around 12% of hash computation.

a little faster hash computation

---

setup/ubuntu_12.04
setup/ubuntu_13.04
setup/ubuntu_13.10
setup/ubuntu_14.04
setup/ubuntu_15.04

The en_US.UTF-8 locale is not generated/installed by default. But since
we have
LANG ?= "en_US.UTF-8"
in conf/shell.conf, any recipe using perl (e.g. linux-headers) ends up
spewing lots of stuff like below to the log.
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
LANGUAGE = (unset),
LC_ALL = (unset),
LC_NUMERIC = "C",
LC_COLLATE = "C",
LANG = "en_US.UTF-8"
are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
It's mostly harmless, but may distract from actual errors. I don't know
if this is an issue on other distributions, nor how to fix it there.

setup/ubuntu*: generate en_US.UTF-8 locale

---

lib/oelite/baker.py

This makes it easier to do all the initial recipe parsing, hash
computation etc. without doing an actual build - this is especially
useful if one is doing some automated testing of a series of meta/core
commits, since one doesn't have to sit and stare at the terminal for a
few minutes waiting to say 'no'. It can also be useful in
non-interactive settings, for example setting up a cheap buildbot job to
do "oe bake world --dryrun" to check that all recipes actually parse,
without doing a full build.

oelite/baker.py: add --dryrun option

---

lib/oelite/meta/dict.py
lib/oelite/pyexec.py

The __hooks variable is a rather complicated data structure, so we save some time and memory by avoiding copying it to the task metadata instances.

A minor memory reduction

---

classes/package-qa.oeclass

In the rare event that the ELF type is not known by libmagic there
should be a definition for the BadElfError being thrown.

packageqa.oeclass: fix error handling

---

lib/oelite/oven.py
lib/oelite/task.py

I left these out of the big parallel PR mostly because I had to draw a line somewhere.

Two leftover oven patches

---

classes/package.oeclass

If there was a broken symlink in the packages directory the code
would decide the file (the symlink) did exist, and then later fail
to replace it. Use the proper python function to handle this case.

package.oeclass: properly handle broken symlinks

---

conf/provided/default.conf
conf/provided/minimal.conf
lib/oelite/fetch/url.py

The underlying problem is that pycurl in ubuntu and debian based
systems are linked with gnutls (instead of openssl)
This results in rror: gnutls_handshake() failed
Signed-off-by: Sean Nyekjaer sean.nyekjaer@prevas.dk

url.py: Replace urlgrabber with a simple syscall to wget

---

lib/oelite/meta/meta.py

Currently, adding a single blank line at the top of core.oeclass or any
other file defining key python functions changes the metadata hash of
_everything_. Try to avoid that by ignoring changes in line numbers in
addition to ignoring the filename. While at it, make the match for
filename a little more stringent.

oelite/meta/meta.py: ignore lineno flag in hash computation

---

classes/chrpath.oeclass
classes/cpio-image.oeclass
classes/crontab.oeclass
classes/gettext.oeclass
classes/kernel.oeclass
classes/runit.oeclass
classes/sdk-image.oeclass
classes/sysvinit.oeclass
conf/distro/uclibc.conf
conf/fstab.conf
conf/inittab.conf
conf/makedevs.conf
lib/oelite/cookbook.py
recipes/base-version/base-version.oe

These patches are all currently semantic noops, but they serve a few purposes: the prefunc/postfunc patches try to standardize on one idiom for running a pre/postfunc dependent on a use flag, and in doing so actually avoids running them if the use flag is not set (as opposed to doing an early return). Other patches change initializations of DEFAULT_USE_foo from using "0"/"1" to using False/True, which the lexer currently treats exactly equivalently (namely, storing the "0"/"1" string as the value), but they serve to document which USE flags are really meant as boolean flags, as opposed to those where the string value is actually used for something.
All patches are also preparation for potential future changes of the USE flag handling and the interpretation of the False/True tokens, but …

Prepare for saner use flag handling

---

recipes/linux-headers/linux-headers_4.4.23.oe
recipes/linux-headers/linux-headers_4.4.23.oe.sig

Bump linux-headers to newest LTS

linux-headers: version bump to 4.4.23

---

classes/core.oeclass
conf/oe-lite.conf
lib/oelite/cookbook.py
lib/oelite/meta/meta.py

This is like BLACKLIST, but a few levels higher in the hierarchy. There are some variables we might as well get rid of before spending time and memory copying them down to layer, recipe and task metadata, only to then spend more time deciding not to hash them.
I'm also going to introduce some variables controlling profiling (to be set in local.conf), and these are also obvious TOPLEVEL stuff.

Introduce TOPLEVEL_VARS

---

lib/oelite/meta/meta.py

No variables called OE_REMOTES, OE_MODULES, OE_REMOTE_* or OE_MODULE_*
have existed since bakery commit 74d7bd345 (which has been in OE bakery
since at least 3.0.0). Getting rid of those means we can remove the
nohash_prefix handling, which in turn saves several million .startswith
calls during hash computation.

lib/oelite/meta/meta.py: remove OE_{REMOTE,MODULE} handling

---

lib/oelite/dicttrim.py
lib/oelite/meta/dict.py
lib/oelite/task.py

It's almost January, so time for the annual diet. Let's include the
dicts backing our metadata instances. This cuts 46% of the memory use of
the .smpl and .cplx members themselves (not accounting for sizes of keys
and values), corresponding to about 10% of the total memory consumption.
For an "oe bake world", that translates to around 63 MB of memory with
the metalayers I have. It doesn't add any noticable time to the
initialization phase.
I admit it's a little hacky, but I think the code-to-comment ratio and
the gain should make up for that. It's a shame Python doesn't expose an
official knob to do this kind of thing.

oelite/meta/dict.py: put our dicts on a diet

---

recipes/binutils/binutils.inc

When building packages manually, one should also set appropriate
PROVIDES_*. Otherwise other recipes start depending on the package
name (binutils-libiberty) rather than the item they really
need (libiberty), needlessly making them dependent on how binutils is
split up.
Signed-off-by: Rasmus Villemoes <rasmus.villemoes@prevas.dk>

binutils: make sure binutils-libiberty provides libiberty

---

classes/stage.oeclass
lib/oelite/cookbook.py
lib/oelite/item.py
lib/oelite/recipe.py

When I did PR#207, I wasn't aware that current OE-lite silently throws away all but the last encountered dependency for a specific item. While explicitly depending on two or more different versions of the same item may be rare, there are certainly use cases, and having the final dependencies depend on the order they appear in DEPENDS / CLASS_DEPENDS is somewhat fragile.
With this, one can do DEPENDS = "bar_3 bar_4" and have both bar_3 and bar_4 staged; if there are file conflicts, do_stage will complain as usual.

allow depending on multiple versions

---

classes/chrpath.oeclass
classes/core.oeclass
classes/elfwrapper.oeclass
classes/image-qa.oeclass
classes/package-qa.oeclass
lib/oelite/magiccache.py

runstrip opens, parses and closes the system's "magic" database for every file it processes, which is somewhat wasteful.
Each do_chrpath leaks the open database handle, which amounts to 700MB+ of extra VM during oe bake world.
Since we only ever use the default database with default flags, just open and parse the database once.

optimize libmagic use

---

classes/kernel.oeclass

Recent kernels add /usr/share/doc/perf-tip/tips.txt; add all current
and future files in the doc/perf-tip directory to perf-doc.

kernel.oeclass: perf: update install files list

---

lib/oelite/baker.py
lib/oelite/cookbook.py

The way "oe bake world" and "oe bake universe" is currently implemented
means that the buildbot spends a lot of time building stuff that is
already known to work.
The problem is (roughly) that when a recipe is a "primary" target,
whether to build it again relies on whether the current do_build stamp
file matches the hash we compute for the do_build task, and the files in
the stamp directory reflect (more or less) the status of $WORKDIR. So
when a PR on meta/core updates gcc [1] the buildbot does a complete
rebuild of everything, which is of course what we want.
However, when another PR comes in which just corrects a wrong LICENSE in
some meta/base recipe, we (of course) use the master branch from
meta/core. Since all the do_build stamp files don't match, we build
everything once again, …

lib/oelite: alternate universe implementation

---

lib/oelite/function.py
lib/oelite/signal.py
lib/oelite/util.py

Python, in order to be able to throw an OSError(EPIPE) exception rather
than terminating directly upon writing to a closed pipe, sets the signal
disposition for SIGPIPE to SIG_IGN. Unfortunately, POSIX specifies under
exec*() that "Except for SIGCHLD, signals set to be ignored (SIG_IGN) by
the calling process image shall be set to be ignored by the new process
image.". This means that, unless some program itself takes an explicit
step to restore the default disposition for SIGPIPE, the entire
subprocess tree will receive -EPIPE upon writing to a closed pipe rather
than being terminated automatically. If some program down the tree,
knowingly or not, relies on the usual behaviour, this can lead to
hard-to-debug errors (or worse, http://bugs.python.org/issue1652).
This is fixed in Python …

lib/oelite: try to avoid subtle SIGPIPE related errors in subprocesses

---

recipes/ncurses/ncurses.inc

I've hit a few problems related to an autoconf script picking up an ncurses[w]-config script from the host. These fix those issues, and I hope (and believe) they won't cause pain elsewhere.

ncurses pkgconfig/binconfig fixups

---

lib/oelite/parse/__init__.py
lib/oelite/parse/confparse.py

The attempt to provide a helpful error message for addhook and other
statements in .conf files fails for a number of reasons. First, the
exception class is not imported into confparse.py, second, the super
statement calls it "StatementNotAllowedInConf" while the class is just
"StatementNotAllowed", and third, the __init__ def lacks the two
trailing underscores, so the ParseError __init__ is anyway called
directly, causing an assert error (after fixing the first two bugs)
since the p argument ends up being passed as the message
parameter.
Since this is only used in confparse.py, I tried moving the exception
class definition to confparse.py, but ran into some cyclic import
issue, so I left it in __init__.py, but still chose the longer name.
Add e.g. "addtask foo" to local.conf to test this. …

oelite/parse: fix "statement not allowed" error reporting

---

classes/fetch.oeclass
lib/oelite/fetch/fetch.py

When we do do_patch, we start by trying to use quilt to undo any
previously applied patches, so that all the patches can be applied
again. Unfortunately there's a few bugs causing this to never really
work.
First of all, util.shcmd returns None for failure and True for
success. So if quilt pop succeeds, we raise an exception claiming that
it failed... Now, if quilt pop fails for some reason, it is likely to
leave the filesystem mostly intact - in particular, .pc/applied-patches
is unlikely to disappear, which means we end up in an infinite loop
running quilt pop over and over.
It turns out that quilt pop _does_ fail to reverse certain patches if
the ${PATCHDIR}/series file has been removed; at first I thought it was
when the patch has a header above the actual diff, but I've also found …

fetch.oeclass: fix patch reversal logic

---

lib/oelite/fetch/url.py

Downloaded files used to be created with mode 0o644 (modified by umask
as usual), but since we now let tempfile.mkstemp do the open(O_CREAT),
we get 0o600. This is a problem at least for mirroring where oe-lite
runs as one user but the webserver runs as another. The simplest way to
fix it up seems to be an explicit fchmod.

oelite/fetch/url.py: fix permissions of generated files

---

classes/libtool.oeclass
recipes/gcc/gcc-common.inc
recipes/gcc/gcc.inc

Resolves errors like:
/bin/sh ../libtool --tag=CXX --mode=link
/bin/grep: work/machine/aarch64-cortexa53t-linux-gnu/some/stage/machine/lib/libstdc++.la: No such file or directory
/bin/sed: can't read work/machine/aarch64-cortexa53t-linux-gnu/some/stage/machine/lib/libstdc++.la: No such file or directory
libtool: error: 'work/machine/aarch64-cortexa53t-linux-gnu/some/stage/machine/lib/libstdc++.la' is not a valid libtool archive
In gcc install we move the sysroot libraries from:
work/cross/aarch64-cortexa53t-linux-gnu/gcc-6.3.0/install/aarch64-cortexa53t-linux-gnu/lib
To:
work/cross/aarch64-cortexa53t-linux-gnu/gcc-6.3.0/install/aarch64-cortexa53t-linux-gnu/sysroot/usr/lib
We do not update the .la files containing fx.:
libdir='/tmp/work/cross/aarch64-cortexa53t-linux-gnu/gcc-6.3.0/install/a …

Fix gcc sysroot .la files

---

lib/oelite/cookbook.py
lib/oelite/meta/dict.py

These patches reduce our memory consumption somewhat as well as make metadata hashing faster. The biggest one is the first which seems to cut 18% of the memory (obviously depending on use flags, architecture etc.); the others are icing I stumbled on a while ago.

metadata: delete various stuff that will never be used

---

classes/mirror.oeclass
lib/oelite/fetch/fetch.py

It may be desirable to exempt some ingredients from being added to a
mirror server. Setting mirror=0 in the SRC_URI is a simple way of
achieving that.

oelite/fetch/fetch.py: allow mirror=0 parameter to avoid mirroring

---

lib/oelite/fetch/git.py

Probably not critical as no-body is crazy enough to actually create files starting with a dash, but just in case... So this is mostly a "while I still remember it", not "jesus christ, how did I ever create that PR".

fetch/git.py: make the mtime fixup more robust

---

classes/kernel.oeclass

I don't believe there are any use of them in kernel-dev packages, and
many of them hardcode path to the originating recipe workdir, which
is obviously bad (with or without rmwork!).
Could/should we remove the .o files also?  Do they serve a purpose in
kernel-dev packages?

class/kernel: Remove those .*.cmd files

---

lib/oelite/cookbook.py

Using pysqlite >= 2.8 (the current version installed via pip is
2.8.3), oe-lite spits out
self.cookbook.db.execute("ATTACH ':memory:' AS runq")
OperationalError: cannot ATTACH database within transaction
CRITICAL: bake failed: Exception: cannot ATTACH database within transaction
during initialization. This is due to a deliberate change in pysqlite
- see commits 94eae5, 90f6fe, cae87e, the latter of which adds the
text
.. versionchanged:: 2.8.0
pysqlite used to implicitly commit an open transaction before DDL statements.
This is no longer the case.
Fix this by completely disabling the "automatically open a
transaction" logic for the database connection. For an in-memory
database that is only accessed by a single process, transactions don't
make much sense anyway. (If we ever wanted to do …

lib/oelite/cookbook.py: open database with isolation_level=None

---

classes/s6rc.oeclass

The s6rc class tracks certain settings for init script with USE flags,
which is handy if a machine or distro wants to override the recipe
defaults.
However, the use of USE flags makes it impossible for the recipe to use
other USE flags to set those s6rc USE flags (confusing wording intended
here).
For example, recipe `initscripts.oe` installs service 'foo-init' that
depends on 'bar-init', but conditionally on a USE flag:
RECIPE_FLAGS += " \
initscripts_foo_init \
foo_init_s6rc_dependencies \
foo_init_s6rc_bundle \
foo_init_s6rc_timeout_up \
foo_init_s6rc_timeout_down \
"
DEFAULT_USE_initscripts_foo_init = "0"
SRC_URI:>USE_initscripts_foo_init = " file://foo-init"
S6RC_ONESHOT_SERVICES:>USE_initscripts_foo_init = " foo-init"
DEFAULT_USE_foo_init_s6rc_dependencies:>USE_initscripts_foo_init …

classes/s6rc: allow use of class variables over USE flags

---

classes/s6rc.oeclass

There's a lot of boilerplate involved in creating an s6 service. On at
least one occation, I missed declaring the *_s6rc_dependencies as a
recipe flag, so the service got created without proper
dependencies. Make this a little less error-prone and allow omitting the
"RECIPE_FLAGS += " lines by automatically defining them based on the
services.
This will of course not work for service names that are added to
S6RC_*_SERVICES depending on a USE flag setting, but there are none of
those currently in meta/base or meta/core, and it is still possible to
manually add to recipe flags.

s6rc.oeclass: automatically declare recipe flags

---

classes/s6rc.oeclass

This is embarrassing. I'm 99% convinced I tested this at some point, but
somehow I've managed to both include a "USE_" prefix which should not be
there as well as leaving out the underscore between the service name and
"s6rc".
Fixes b4330e6 - s6rc.oeclass: automatically declare flags

s6rc.oeclass: automatically declare the correct flags

---

classes/chrpath.oeclass

When a file has the setuid/setgid bits set, filemagic returns a string
such as
setuid, setgid ELF 32-bit LSB executable, ARM...
but in chrpath_get_cmd, we look for the regexp "ELF 32-bit ..." using
.match, which (contrary to .search) implicitly anchors the regexp at
the beginning. Hence we fail to return a chrpath command to use.
At first, I tried to fix this by either using .search, or by removing
leading occurences of "setuid,? ?", "setgid,? ?" in the filetype argument
in chrpath_get_cmd. However, it turns out that if we end up doing the
"chrpath -d" or whatnot, the kernel automatically clears the
setuid/setgid bits, so we'd have to restore them manually anyway in
do_chrpath. So since we already have a little chmod logic there, extend
the read-write test to also insist that the …

chrpath.oeclass: fix for setuid/setgid files

---

classes/elfwrapper.oeclass

Avoid forking of, making a bit more convenient to keep track of the PID
of the process.

class/elfwrapper: Do not fork

---

classes/elfwrapper.oeclass

When calling the wrapped command, set argv[0] to the wrapper
argv[0] instead of the full path to the wrapped command.
This should be safer, as argv[0] can be used by the wrapped
command (where as the full path to the wrapped command is not
safe to call directly).  Also, commands using argv[0] for usage
information looks nicer.

class/elfwrapper: Set argv[0] to wrapper instead of wrapped cmd

---

classes/manifest-version.oeclass

This changes the behavior of USE_manifest_version_strip_leading, so that only
tags that matches this will be used.
With the previous behavior, the latest tag would always be used, and if it
matched, would be stripped accordingly.  For non-matching tags, they would
just be used as-is.
With this new behavior, the USE_manifest_version_strip_leading can be safely
used with the initial intent, which is to use it for for relase versioning
using tags with a specific prefix.  The OESTACK_VERSION will always be taken
as relative to the latest release, even if other type of (non-release) tags
have been added since then.

class/manifest-version: Only consider matching tags

---

classes/s6rc.oeclass

This fixes problems for recipes using s6rc.oeclass without any
RECIPE_FLAGS, as we will try to do None.split().
```
Traceback (most recent call last):
File "/home/user/manifest/meta/core/lib/oelite/cookbook.py", line 57, in __init__
if not self.add_recipefile(recipefile):
File "/home/user/manifest/meta/core/lib/oelite/cookbook.py", line 554, in add_recipefile
recipe_meta = self.parse_recipe(filename)
File "/home/user/manifest/meta/core/lib/oelite/cookbook.py", line 683, in parse_recipe
oelite.pyexec.exechooks(meta[recipe_type], "post_recipe_parse")
File "/home/user/manifest/meta/core/lib/oelite/pyexec.py", line 44, in exechooks
retval = hook.run(tmpdir)
File "/home/user/manifest/meta/core/lib/oelite/function.py", line 37, in run
self.start(cwd)
File …
```

class/s6rc: Fix bug when RECIPE_FLAGS is not set

---

classes/kernel.oeclass

The localversion-rt file is used by some buildsystems to know the
RT-Preempt baseline that a kernel is based on.

class/kernel: Include localversion-rt in kernel-dev package

---

classes/auto-package-libs.oeclass

This makes sure that all recipes using auto-package-libs provides also
provides a LIBRARY_VERSION specific -dev item.
This is necessary when RDEPENDS_ for -dev packages are generated by
auto-package-libs.oeclass based on the normal package RDEPENDS, and when
these contains LIBRARY_VERSION specific dependencies.

class/auto-package-libs: LIBRARY_VERSION specific -dev package provides

---

classes/meson.oeclass

Using meson requires installing ninja as well as python > 3.5.  
meson it self must also be installed via pip.
Disclaimer, this is only tested with arm target and with the gssdp package, see PR for that: https://github.com/oe-lite/base/pull/594
Signed-off-by: Kjeld Flarup <kfa@deif.com>

Add support for the meson build system, used with ex. gnome packages.

---

classes/kernel.oeclass

Some versions of perf do not build cleanly with certain gccs (e.g., an
old perf may trigger warnings/errors in new gccs). Since perf by
default uses -Werror, that breaks the entire build.
This adds an escape hatch so that one can say
EXTRA_OEMAKE_PERF = "WERROR=0"
in the kernel recipe to disable -Werror. Obviously, it can also be
used for other things.

kernel.oeclass: add escape hatch when building perf
