site/mingw32
=> Add mingw32 site info

conf/distro/common.inc, conf/distro/glibc.conf, conf/distro/mingw32.conf, conf/distro/uclibc.conf
=> conf: Remove unused ct-NG related USE flags

recipes/libtool/libtool_2.2.10.oe.sig
=> libtool: Remove old sig

classes/dupdate-image.oeclass
=> class/dupdate-image: Pull in zip command

recipes/glibc/glibc-2.21/git-65f6f938-o-tmpfile-flags.patch, recipes/glibc/glibc_2.21.oe
=> glibc: Add patch from upstream to fix O_TMPFILE flag handling

classes/squashfs-image.oeclass
=> squashfs: Fix rebuild of squashfs images

classes/c.oeclass
=> class/c: Add 'c' override

classes/kernel.oeclass, lib/oelite/arch.py
=> 64bit sdk fix, kernel newer than 4.0 fix, arch.py cleanup

recipes/make/make.inc
Signed-off-by: Sean Nyekjaer <sean.nyekjaer@prevas.dk>
=> make: packageqa fixes

recipes/glibc/glibc-2.21/git-59b61c82-o-tmpfile-nondefault-arch.patch, recipes/glibc/glibc_2.21.oe
=> glibc: Fix O_TMPFILE bug on ARM and other architectures

recipes/patchelf/patchelf.inc, recipes/patchelf/patchelf_0.8.oe, recipes/patchelf/patchelf_0.8.oe.sig
Patchelf for patching elf files. Used in sdk setup script for setting ld.so path.
=> patchelf: Added

lib/oelite/baker.py
=> lib/oelite: Add debug info on EXTRA_ARCH resolving deadlock

recipes/ncurses/ncurses.inc
Signed-off-by: Christian Sørensen <christian.braunersorensen@prevas.dk>
=> ncurses: Remove link from lafile

classes/pkgconfig-install.oeclass
Signed-off-by: Christian Sørensen <christian.braunersorensen@prevas.dk>
=> class/pkgconfig-install: Fixup pkgconfig files

classes/s6rc.oeclass
=> class/s6rc: Fix error handling

lib/oelite/baker.py, lib/oelite/cookbook.py, lib/oelite/dbutil.py, lib/oelite/meta/dict.py, lib/oelite/meta/meta.py, lib/oelite/package.py, lib/oelite/parse/oeparse.py, lib/oelite/runq.py, lib/oelite/task.py, lib/oelite/util.py
Here's a bunch of semi-low hanging fruit. I think they are all "obviously" correct, but someone should probably check. For me, an "oe bake world" on current master takes ~4m54s to get to the "Do you want to continue" prompt, with these patches, that's down to ~2m10s. The biggest contributor is  	0e1f20a, but the others also cut some seconds here and there.
=> Make it even faster

conf/mirrors.conf
=> conf/mirrors: Allow mirroring of https URLs

classes/squashfs-image.oeclass, recipes/squashfs/squashfs-tools.inc
=> squashfs-tools: Fix enable of multiple compressors and lzo dependency

lib/oelite/cookbook.py, lib/oelite/dbutil.py, lib/oelite/meta/dict.py, lib/oelite/meta/meta.py, lib/oelite/profiling.py, lib/oelite/runq.py, lib/oelite/task.py
These patches don't really do anything, except add more profiling infrastructure and uses of the existing. These have formed the base of some the recent performance PRs, but I'm pretty sure there's still more to gain, so I'd like to have these upstream.
=> more profiling

lib/oelite/task.py, lib/oelite/util.py
The first three are mostly cosmetic, but also adds a little hardening and a very small performance benefit. The fourth is what I believe to be the proper fix for something that was hacked around in oebakery eons ago.
=> Some file descriptor tweaks

classes/core.oeclass, classes/package.oeclass, classes/runit.oeclass
Combined with PR #194 , these should eliminate the last uses of bb.data in meta/core. There are still some in meta/base, but they're just as easy to get rid of.
=> Remove use of bb.data.getVar

lib/oelite/fetch/git.py
This fixes a subtle and hard-to-reproduce error when building the linux
kernel and modules, and should be The Right Thing To Do in general. The
symptom, when the bug appears, is that the kernel is built with some
version string "4.5.6-01234-g0abcdef", but the modules (both the native
kernel modules and those built externally using the linux-dev package)
end up in /lib/modules/4.5.6-01234-g0abcdef-dirty.
The problem turned out to be that when we do 'git checkout -q', the
files
arch/arm/crypto/aesbs-core.S_shipped
arch/arm/crypto/bsaes-armv7.pl
sometimes ended up with the latter being newer than the former (in the
vast majority of cases, their mtimes are identical due to the limited
resolution of filesystem timestamps), which in turn causes the kernel
build system to (re)generate …
=> fetch/git.py: uniformize mtimes of checked-out files

classes/image_ldconfig.oeclass, classes/qemu-cpu.oeclass, recipes/qemu/qemu.inc, recipes/qemu/qemu_2.8.1.1.oe, recipes/qemu/qemu_2.8.1.1.oe.sig
I haven't tested this much, but it does end up building a usable root file system.
=> qemu and class for build-time ld.so.cache creation

classes/elfwrapper.oeclass
=> Revert "class/elfwrapper: Set argv[0] to wrapper instead of wrapped cmd"

classes/kernel.oeclass
=> class/kernel: Expand tabs to 8 spaces
